@startuml
Alumno  --> "*" Materia : materiasAprobadas
Inscripcion *-- Alumno : alumno
Inscripcion  --> "*" Materia : materiasQueSeQuiereAnotar
Materia  --> "*" Materia : correlativas


class Alumno {
    private List<Materia> materiasAprobadas;
    public Alumno(List<Materia> materiasAprobadas) {}
    public boolean pudeCursarla(Materia materia) {}
}

class Inscripcion {
    private Alumno alumno;
    private List<Materia> materiasQueSeQuiereAnotar;
    public Inscripcion(Alumno alumno, List<Materia> materias) {}
    public boolean aprobo() {}
}

class Materia {
    private List<Materia> correlativas;
    public Materia(List<Materia> correlativas) {}
    public List<Materia> getCorrelativas() {}
}

@enduml
